### PR TITLE
Private methods that don't access instance data should be 'static'

### PR DESCRIPTION
**Pull request by zeeshanasghar**
This pull request is focused on resolving occurrences of Sonar rule 

squid:S2325 'private' methods that don't access instance data should be 'static'

You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2325

Please let me know if you have any questions.

Zeeshan Asghar

### CODE REVIEW

**Comment by peholmst** [comment]
I'm not merging this pull request. The java serialization methods readObject and writeObject cannot be static. Please remove that change. The rest of the methods are probably OK.

**Comment by christoph-frick** [comment]
then they also don't need to be private

**Comment by peholmst** [comment]
Do you mean the serialization methods? From what I've read in the JavaDocs of the Serializable interface, readObject and writeObject should explicitly be private. Please correct me if I'm wrong.

**Comment by christoph-frick** [comment]
sorry, i meant "all of them". i don't see any gain in hiding pure functions

**Comment by peholmst** [comment]
I'm not sure I agree with that. Functions and methods that are part of the public API should of course be available. Then you should also make sure that you don't accidentally break the public API in subsequent updates, unless you intend to. Many functions are intended for internal use only and if you expose them, other developers might start to use them in ways you did not anticipate. When you refactor your code in the future and end up removing some of those public internal functions, you'll end up with angry developers whose applications are no longer compatible with your updated code.

**Comment by zeeshanasghar** [comment]
@peholmst PR updated.

**Pull request merged**
