### PR TITLE
Vaadin 1.1.0 upgrade and making some dependencies provided in extensions

### PR DESCRIPTION
**Pull request by mstahv**
Should probably go through all extensions later and see what can be made provided.

### CODE REVIEW

**Comment by mstahv** [comment]
@snicoll, would this (  [beff628] ) be the correct way, not to let development versions from vaadin4spring to leak to application projects?

**Comment by snicoll** [comment]
I am not sure I understand but if you want to prevent the issue we had regarding the upgrade, the only proper way to fix that is to have a BOM. I've asked Henri and he created an issue for that.

IMO that change is bad because a required dependency is no longer provided transitively.

**Comment by mstahv** [comment]
That's true, but I guess most often vaadin-spring comes via starter or direct vaadin-spring dependency. I don't see that big difference to e.g. servlet/java-ee dependencies with traditional war projects. @peholmst might have some insights how your projects are currently configured?

**Comment by snicoll** [comment]
That's no reason to alter the pom of your project IMO. Flagging a dependency as `provided` really means that someone else is going to provide it and you don't need to bring it transitively. What we're trying to fix here is to make sure dependency versions are consistent. 

I do see a major difference compared to the servlet api. Your container is not going to provide `vaadin-spring` at all...

**Comment by mstahv** [comment]
Yep, true, it is the spring app which brings in vaadin-spring, spring-web etc. Not so sure how big the difference is with spring boot thought as the server itself comes with the app :-) If dependency management would just be as easy as development...

I'll split the changes to get the vaadin-spring version update though.

**Comment by mstahv** [comment]
@peholmst I force pushed and now this seems to be updated, not to contain the "provided hack" for not overriding versions in app projects.

**Pull request merged**
