### PR TITLE
When running with spring boot devtools the application cannot be rest…

### PR DESCRIPTION
**Pull request by aspan**
…arted because the application context can't be set in the VaadinApplicationContext.

### CODE REVIEW

**Comment by peholmst** [comment]
Could you please add a WARN log entry or something similar instead of the exception?

**Comment by aspan** [comment]
I'll update the pull request

**Comment by peholmst** [comment]
Thanks!

**Comment by aspan** [comment]
I've updated the code to log a warning instead of throwing an exception now.

Best Regards
Andreas Asplund

**Comment by peholmst** [comment]
Thanks!

**Pull request merged**
